// Code generated by MockGen. DO NOT EDIT.
// Source: /home/mlb/github/SSPT/internal/database/interface.go

// Package database is a generated GoMock package.
package database

import (
	context "context"
	reflect "reflect"

	models "github.com/akyairhashvil/SSPT/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockGoalRepository is a mock of GoalRepository interface.
type MockGoalRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGoalRepositoryMockRecorder
}

// MockGoalRepositoryMockRecorder is the mock recorder for MockGoalRepository.
type MockGoalRepositoryMockRecorder struct {
	mock *MockGoalRepository
}

// NewMockGoalRepository creates a new mock instance.
func NewMockGoalRepository(ctrl *gomock.Controller) *MockGoalRepository {
	mock := &MockGoalRepository{ctrl: ctrl}
	mock.recorder = &MockGoalRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGoalRepository) EXPECT() *MockGoalRepositoryMockRecorder {
	return m.recorder
}

// AddGoal mocks base method.
func (m *MockGoalRepository) AddGoal(ctx context.Context, workspaceID int64, description string, sprintID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddGoal", ctx, workspaceID, description, sprintID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddGoal indicates an expected call of AddGoal.
func (mr *MockGoalRepositoryMockRecorder) AddGoal(ctx, workspaceID, description, sprintID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddGoal", reflect.TypeOf((*MockGoalRepository)(nil).AddGoal), ctx, workspaceID, description, sprintID)
}

// AddGoalDetailed mocks base method.
func (m *MockGoalRepository) AddGoalDetailed(ctx context.Context, workspaceID, sprintID int64, seed GoalSeed) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddGoalDetailed", ctx, workspaceID, sprintID, seed)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddGoalDetailed indicates an expected call of AddGoalDetailed.
func (mr *MockGoalRepositoryMockRecorder) AddGoalDetailed(ctx, workspaceID, sprintID, seed interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddGoalDetailed", reflect.TypeOf((*MockGoalRepository)(nil).AddGoalDetailed), ctx, workspaceID, sprintID, seed)
}

// AddSubtask mocks base method.
func (m *MockGoalRepository) AddSubtask(ctx context.Context, description string, parentID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSubtask", ctx, description, parentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddSubtask indicates an expected call of AddSubtask.
func (mr *MockGoalRepositoryMockRecorder) AddSubtask(ctx, description, parentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSubtask", reflect.TypeOf((*MockGoalRepository)(nil).AddSubtask), ctx, description, parentID)
}

// AddSubtaskDetailed mocks base method.
func (m *MockGoalRepository) AddSubtaskDetailed(ctx context.Context, parentID int64, seed GoalSeed) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSubtaskDetailed", ctx, parentID, seed)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddSubtaskDetailed indicates an expected call of AddSubtaskDetailed.
func (mr *MockGoalRepositoryMockRecorder) AddSubtaskDetailed(ctx, parentID, seed interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSubtaskDetailed", reflect.TypeOf((*MockGoalRepository)(nil).AddSubtaskDetailed), ctx, parentID, seed)
}

// DeleteGoal mocks base method.
func (m *MockGoalRepository) DeleteGoal(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGoal", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGoal indicates an expected call of DeleteGoal.
func (mr *MockGoalRepositoryMockRecorder) DeleteGoal(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGoal", reflect.TypeOf((*MockGoalRepository)(nil).DeleteGoal), ctx, id)
}

// GetBacklogGoals mocks base method.
func (m *MockGoalRepository) GetBacklogGoals(ctx context.Context, workspaceID int64) ([]models.Goal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBacklogGoals", ctx, workspaceID)
	ret0, _ := ret[0].([]models.Goal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBacklogGoals indicates an expected call of GetBacklogGoals.
func (mr *MockGoalRepositoryMockRecorder) GetBacklogGoals(ctx, workspaceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBacklogGoals", reflect.TypeOf((*MockGoalRepository)(nil).GetBacklogGoals), ctx, workspaceID)
}

// GetGoalsForSprint mocks base method.
func (m *MockGoalRepository) GetGoalsForSprint(ctx context.Context, sprintID int64) ([]models.Goal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGoalsForSprint", ctx, sprintID)
	ret0, _ := ret[0].([]models.Goal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGoalsForSprint indicates an expected call of GetGoalsForSprint.
func (mr *MockGoalRepositoryMockRecorder) GetGoalsForSprint(ctx, sprintID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGoalsForSprint", reflect.TypeOf((*MockGoalRepository)(nil).GetGoalsForSprint), ctx, sprintID)
}

// UpdateGoalStatus mocks base method.
func (m *MockGoalRepository) UpdateGoalStatus(ctx context.Context, goalID int64, status models.GoalStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGoalStatus", ctx, goalID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateGoalStatus indicates an expected call of UpdateGoalStatus.
func (mr *MockGoalRepositoryMockRecorder) UpdateGoalStatus(ctx, goalID, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGoalStatus", reflect.TypeOf((*MockGoalRepository)(nil).UpdateGoalStatus), ctx, goalID, status)
}

// MockSprintRepository is a mock of SprintRepository interface.
type MockSprintRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSprintRepositoryMockRecorder
}

// MockSprintRepositoryMockRecorder is the mock recorder for MockSprintRepository.
type MockSprintRepositoryMockRecorder struct {
	mock *MockSprintRepository
}

// NewMockSprintRepository creates a new mock instance.
func NewMockSprintRepository(ctrl *gomock.Controller) *MockSprintRepository {
	mock := &MockSprintRepository{ctrl: ctrl}
	mock.recorder = &MockSprintRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSprintRepository) EXPECT() *MockSprintRepositoryMockRecorder {
	return m.recorder
}

// AppendSprint mocks base method.
func (m *MockSprintRepository) AppendSprint(ctx context.Context, dayID, workspaceID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendSprint", ctx, dayID, workspaceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendSprint indicates an expected call of AppendSprint.
func (mr *MockSprintRepositoryMockRecorder) AppendSprint(ctx, dayID, workspaceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendSprint", reflect.TypeOf((*MockSprintRepository)(nil).AppendSprint), ctx, dayID, workspaceID)
}

// BootstrapDay mocks base method.
func (m *MockSprintRepository) BootstrapDay(ctx context.Context, workspaceID int64, numSprints int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BootstrapDay", ctx, workspaceID, numSprints)
	ret0, _ := ret[0].(error)
	return ret0
}

// BootstrapDay indicates an expected call of BootstrapDay.
func (mr *MockSprintRepositoryMockRecorder) BootstrapDay(ctx, workspaceID, numSprints interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BootstrapDay", reflect.TypeOf((*MockSprintRepository)(nil).BootstrapDay), ctx, workspaceID, numSprints)
}

// CompleteSprint mocks base method.
func (m *MockSprintRepository) CompleteSprint(ctx context.Context, sprintID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteSprint", ctx, sprintID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteSprint indicates an expected call of CompleteSprint.
func (mr *MockSprintRepositoryMockRecorder) CompleteSprint(ctx, sprintID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteSprint", reflect.TypeOf((*MockSprintRepository)(nil).CompleteSprint), ctx, sprintID)
}

// GetSprints mocks base method.
func (m *MockSprintRepository) GetSprints(ctx context.Context, dayID, workspaceID int64) ([]models.Sprint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSprints", ctx, dayID, workspaceID)
	ret0, _ := ret[0].([]models.Sprint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSprints indicates an expected call of GetSprints.
func (mr *MockSprintRepositoryMockRecorder) GetSprints(ctx, dayID, workspaceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSprints", reflect.TypeOf((*MockSprintRepository)(nil).GetSprints), ctx, dayID, workspaceID)
}

// PauseSprint mocks base method.
func (m *MockSprintRepository) PauseSprint(ctx context.Context, sprintID int64, elapsedSeconds int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PauseSprint", ctx, sprintID, elapsedSeconds)
	ret0, _ := ret[0].(error)
	return ret0
}

// PauseSprint indicates an expected call of PauseSprint.
func (mr *MockSprintRepositoryMockRecorder) PauseSprint(ctx, sprintID, elapsedSeconds interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PauseSprint", reflect.TypeOf((*MockSprintRepository)(nil).PauseSprint), ctx, sprintID, elapsedSeconds)
}

// RemoveLastSprint mocks base method.
func (m *MockSprintRepository) RemoveLastSprint(ctx context.Context, dayID, workspaceID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveLastSprint", ctx, dayID, workspaceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveLastSprint indicates an expected call of RemoveLastSprint.
func (mr *MockSprintRepositoryMockRecorder) RemoveLastSprint(ctx, dayID, workspaceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveLastSprint", reflect.TypeOf((*MockSprintRepository)(nil).RemoveLastSprint), ctx, dayID, workspaceID)
}

// ResetSprint mocks base method.
func (m *MockSprintRepository) ResetSprint(ctx context.Context, sprintID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetSprint", ctx, sprintID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetSprint indicates an expected call of ResetSprint.
func (mr *MockSprintRepositoryMockRecorder) ResetSprint(ctx, sprintID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetSprint", reflect.TypeOf((*MockSprintRepository)(nil).ResetSprint), ctx, sprintID)
}

// StartSprint mocks base method.
func (m *MockSprintRepository) StartSprint(ctx context.Context, sprintID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartSprint", ctx, sprintID)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartSprint indicates an expected call of StartSprint.
func (mr *MockSprintRepositoryMockRecorder) StartSprint(ctx, sprintID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartSprint", reflect.TypeOf((*MockSprintRepository)(nil).StartSprint), ctx, sprintID)
}

// MockWorkspaceRepository is a mock of WorkspaceRepository interface.
type MockWorkspaceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWorkspaceRepositoryMockRecorder
}

// MockWorkspaceRepositoryMockRecorder is the mock recorder for MockWorkspaceRepository.
type MockWorkspaceRepositoryMockRecorder struct {
	mock *MockWorkspaceRepository
}

// NewMockWorkspaceRepository creates a new mock instance.
func NewMockWorkspaceRepository(ctrl *gomock.Controller) *MockWorkspaceRepository {
	mock := &MockWorkspaceRepository{ctrl: ctrl}
	mock.recorder = &MockWorkspaceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkspaceRepository) EXPECT() *MockWorkspaceRepositoryMockRecorder {
	return m.recorder
}

// CreateWorkspace mocks base method.
func (m *MockWorkspaceRepository) CreateWorkspace(ctx context.Context, name, slug string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWorkspace", ctx, name, slug)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWorkspace indicates an expected call of CreateWorkspace.
func (mr *MockWorkspaceRepositoryMockRecorder) CreateWorkspace(ctx, name, slug interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorkspace", reflect.TypeOf((*MockWorkspaceRepository)(nil).CreateWorkspace), ctx, name, slug)
}

// EnsureDefaultWorkspace mocks base method.
func (m *MockWorkspaceRepository) EnsureDefaultWorkspace(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureDefaultWorkspace", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsureDefaultWorkspace indicates an expected call of EnsureDefaultWorkspace.
func (mr *MockWorkspaceRepositoryMockRecorder) EnsureDefaultWorkspace(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureDefaultWorkspace", reflect.TypeOf((*MockWorkspaceRepository)(nil).EnsureDefaultWorkspace), ctx)
}

// GetWorkspaces mocks base method.
func (m *MockWorkspaceRepository) GetWorkspaces(ctx context.Context) ([]models.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaces", ctx)
	ret0, _ := ret[0].([]models.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkspaces indicates an expected call of GetWorkspaces.
func (mr *MockWorkspaceRepositoryMockRecorder) GetWorkspaces(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaces", reflect.TypeOf((*MockWorkspaceRepository)(nil).GetWorkspaces), ctx)
}

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddGoal mocks base method.
func (m *MockRepository) AddGoal(ctx context.Context, workspaceID int64, description string, sprintID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddGoal", ctx, workspaceID, description, sprintID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddGoal indicates an expected call of AddGoal.
func (mr *MockRepositoryMockRecorder) AddGoal(ctx, workspaceID, description, sprintID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddGoal", reflect.TypeOf((*MockRepository)(nil).AddGoal), ctx, workspaceID, description, sprintID)
}

// AddGoalDetailed mocks base method.
func (m *MockRepository) AddGoalDetailed(ctx context.Context, workspaceID, sprintID int64, seed GoalSeed) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddGoalDetailed", ctx, workspaceID, sprintID, seed)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddGoalDetailed indicates an expected call of AddGoalDetailed.
func (mr *MockRepositoryMockRecorder) AddGoalDetailed(ctx, workspaceID, sprintID, seed interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddGoalDetailed", reflect.TypeOf((*MockRepository)(nil).AddGoalDetailed), ctx, workspaceID, sprintID, seed)
}

// AddSubtask mocks base method.
func (m *MockRepository) AddSubtask(ctx context.Context, description string, parentID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSubtask", ctx, description, parentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddSubtask indicates an expected call of AddSubtask.
func (mr *MockRepositoryMockRecorder) AddSubtask(ctx, description, parentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSubtask", reflect.TypeOf((*MockRepository)(nil).AddSubtask), ctx, description, parentID)
}

// AddSubtaskDetailed mocks base method.
func (m *MockRepository) AddSubtaskDetailed(ctx context.Context, parentID int64, seed GoalSeed) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSubtaskDetailed", ctx, parentID, seed)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddSubtaskDetailed indicates an expected call of AddSubtaskDetailed.
func (mr *MockRepositoryMockRecorder) AddSubtaskDetailed(ctx, parentID, seed interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSubtaskDetailed", reflect.TypeOf((*MockRepository)(nil).AddSubtaskDetailed), ctx, parentID, seed)
}

// AppendSprint mocks base method.
func (m *MockRepository) AppendSprint(ctx context.Context, dayID, workspaceID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendSprint", ctx, dayID, workspaceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendSprint indicates an expected call of AppendSprint.
func (mr *MockRepositoryMockRecorder) AppendSprint(ctx, dayID, workspaceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendSprint", reflect.TypeOf((*MockRepository)(nil).AppendSprint), ctx, dayID, workspaceID)
}

// BootstrapDay mocks base method.
func (m *MockRepository) BootstrapDay(ctx context.Context, workspaceID int64, numSprints int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BootstrapDay", ctx, workspaceID, numSprints)
	ret0, _ := ret[0].(error)
	return ret0
}

// BootstrapDay indicates an expected call of BootstrapDay.
func (mr *MockRepositoryMockRecorder) BootstrapDay(ctx, workspaceID, numSprints interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BootstrapDay", reflect.TypeOf((*MockRepository)(nil).BootstrapDay), ctx, workspaceID, numSprints)
}

// CompleteSprint mocks base method.
func (m *MockRepository) CompleteSprint(ctx context.Context, sprintID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteSprint", ctx, sprintID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteSprint indicates an expected call of CompleteSprint.
func (mr *MockRepositoryMockRecorder) CompleteSprint(ctx, sprintID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteSprint", reflect.TypeOf((*MockRepository)(nil).CompleteSprint), ctx, sprintID)
}

// CreateWorkspace mocks base method.
func (m *MockRepository) CreateWorkspace(ctx context.Context, name, slug string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWorkspace", ctx, name, slug)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWorkspace indicates an expected call of CreateWorkspace.
func (mr *MockRepositoryMockRecorder) CreateWorkspace(ctx, name, slug interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorkspace", reflect.TypeOf((*MockRepository)(nil).CreateWorkspace), ctx, name, slug)
}

// DeleteGoal mocks base method.
func (m *MockRepository) DeleteGoal(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGoal", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGoal indicates an expected call of DeleteGoal.
func (mr *MockRepositoryMockRecorder) DeleteGoal(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGoal", reflect.TypeOf((*MockRepository)(nil).DeleteGoal), ctx, id)
}

// EnsureDefaultWorkspace mocks base method.
func (m *MockRepository) EnsureDefaultWorkspace(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureDefaultWorkspace", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsureDefaultWorkspace indicates an expected call of EnsureDefaultWorkspace.
func (mr *MockRepositoryMockRecorder) EnsureDefaultWorkspace(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureDefaultWorkspace", reflect.TypeOf((*MockRepository)(nil).EnsureDefaultWorkspace), ctx)
}

// GetBacklogGoals mocks base method.
func (m *MockRepository) GetBacklogGoals(ctx context.Context, workspaceID int64) ([]models.Goal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBacklogGoals", ctx, workspaceID)
	ret0, _ := ret[0].([]models.Goal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBacklogGoals indicates an expected call of GetBacklogGoals.
func (mr *MockRepositoryMockRecorder) GetBacklogGoals(ctx, workspaceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBacklogGoals", reflect.TypeOf((*MockRepository)(nil).GetBacklogGoals), ctx, workspaceID)
}

// GetGoalsForSprint mocks base method.
func (m *MockRepository) GetGoalsForSprint(ctx context.Context, sprintID int64) ([]models.Goal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGoalsForSprint", ctx, sprintID)
	ret0, _ := ret[0].([]models.Goal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGoalsForSprint indicates an expected call of GetGoalsForSprint.
func (mr *MockRepositoryMockRecorder) GetGoalsForSprint(ctx, sprintID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGoalsForSprint", reflect.TypeOf((*MockRepository)(nil).GetGoalsForSprint), ctx, sprintID)
}

// GetSprints mocks base method.
func (m *MockRepository) GetSprints(ctx context.Context, dayID, workspaceID int64) ([]models.Sprint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSprints", ctx, dayID, workspaceID)
	ret0, _ := ret[0].([]models.Sprint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSprints indicates an expected call of GetSprints.
func (mr *MockRepositoryMockRecorder) GetSprints(ctx, dayID, workspaceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSprints", reflect.TypeOf((*MockRepository)(nil).GetSprints), ctx, dayID, workspaceID)
}

// GetWorkspaces mocks base method.
func (m *MockRepository) GetWorkspaces(ctx context.Context) ([]models.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaces", ctx)
	ret0, _ := ret[0].([]models.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkspaces indicates an expected call of GetWorkspaces.
func (mr *MockRepositoryMockRecorder) GetWorkspaces(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaces", reflect.TypeOf((*MockRepository)(nil).GetWorkspaces), ctx)
}

// PauseSprint mocks base method.
func (m *MockRepository) PauseSprint(ctx context.Context, sprintID int64, elapsedSeconds int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PauseSprint", ctx, sprintID, elapsedSeconds)
	ret0, _ := ret[0].(error)
	return ret0
}

// PauseSprint indicates an expected call of PauseSprint.
func (mr *MockRepositoryMockRecorder) PauseSprint(ctx, sprintID, elapsedSeconds interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PauseSprint", reflect.TypeOf((*MockRepository)(nil).PauseSprint), ctx, sprintID, elapsedSeconds)
}

// RemoveLastSprint mocks base method.
func (m *MockRepository) RemoveLastSprint(ctx context.Context, dayID, workspaceID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveLastSprint", ctx, dayID, workspaceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveLastSprint indicates an expected call of RemoveLastSprint.
func (mr *MockRepositoryMockRecorder) RemoveLastSprint(ctx, dayID, workspaceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveLastSprint", reflect.TypeOf((*MockRepository)(nil).RemoveLastSprint), ctx, dayID, workspaceID)
}

// ResetSprint mocks base method.
func (m *MockRepository) ResetSprint(ctx context.Context, sprintID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetSprint", ctx, sprintID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetSprint indicates an expected call of ResetSprint.
func (mr *MockRepositoryMockRecorder) ResetSprint(ctx, sprintID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetSprint", reflect.TypeOf((*MockRepository)(nil).ResetSprint), ctx, sprintID)
}

// StartSprint mocks base method.
func (m *MockRepository) StartSprint(ctx context.Context, sprintID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartSprint", ctx, sprintID)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartSprint indicates an expected call of StartSprint.
func (mr *MockRepositoryMockRecorder) StartSprint(ctx, sprintID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartSprint", reflect.TypeOf((*MockRepository)(nil).StartSprint), ctx, sprintID)
}

// UpdateGoalStatus mocks base method.
func (m *MockRepository) UpdateGoalStatus(ctx context.Context, goalID int64, status models.GoalStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGoalStatus", ctx, goalID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateGoalStatus indicates an expected call of UpdateGoalStatus.
func (mr *MockRepositoryMockRecorder) UpdateGoalStatus(ctx, goalID, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGoalStatus", reflect.TypeOf((*MockRepository)(nil).UpdateGoalStatus), ctx, goalID, status)
}
