package tui

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/akyairhashvil/SSPT/internal/database"
	"github.com/akyairhashvil/SSPT/internal/util"
)

// GenerateReport creates a markdown summary of the day's activity.
func GenerateReport(db *database.Database, dayID int64, workspaceID int64) (string, error) {
	day, err := db.GetDay(dayID)
	if err != nil {
		return "", err
	}
	sprints, err := db.GetSprints(dayID, workspaceID)
	if err != nil {
		return "", err
	}

	reportRoot := util.ReportsDir("sspt")
	if err := os.MkdirAll(reportRoot, 0o755); err != nil {
		return "", err
	}
	filename := filepath.Join(reportRoot, fmt.Sprintf("productivity_%s.md", day.Date))

	// Get absolute path for clarity in the print output
	absPath, err := filepath.Abs(filename)
	if err != nil {
		return "", err
	}

	f, err := os.Create(filename)
	if err != nil {
		return "", err
	}
	defer f.Close()
	write := func(content string) error {
		_, err := f.WriteString(content)
		return err
	}

	// Header
	if err := write(fmt.Sprintf("# Productivity Report: %s\n\n", day.Date)); err != nil {
		return "", err
	}
	if err := write("Generated by SSPT (Simple Sprint Productivity Tool)\n\n"); err != nil {
		return "", err
	}

	totalCompleted := 0
	totalGoals := 0

	// Fetch ALL goals to build complete context
	allGoals, err := db.GetAllGoals()
	if err != nil {
		return "", err
	}
	masterTree := BuildHierarchy(allGoals)

	// Helper to check relevancy
	var isRelevant func(g GoalView, sprintID int64) bool
	isRelevant = func(g GoalView, sprintID int64) bool {
		if g.SprintID != nil && *g.SprintID == sprintID {
			return true
		}
		for _, sub := range g.Subtasks {
			if isRelevant(sub, sprintID) {
				return true
			}
		}
		return false
	}

	formatElapsed := func(seconds int) string {
		if seconds <= 0 {
			return ""
		}
		h := seconds / 3600
		m := (seconds % 3600) / 60
		s := seconds % 60
		return fmt.Sprintf(" [time %02d:%02d:%02d]", h, m, s)
	}

	// Iterate Sprints
	for _, s := range sprints {
		// Filter MasterTree for this sprint
		var relevantRoots []GoalView
		for _, root := range masterTree {
			if isRelevant(root, s.ID) {
				relevantRoots = append(relevantRoots, root)
			}
		}

		flatGoals := Flatten(relevantRoots, 0, nil, 0) // Expand all

		timeRange := "Pending"
		if s.StartTime != nil {
			start := s.StartTime.Format("15:04")
			end := "??"
			if s.EndTime != nil {
				end = s.EndTime.Format("15:04")
			}
			timeRange = fmt.Sprintf("%s - %s", start, end)
		}

		if err := write(fmt.Sprintf("## Sprint %d (%s)\n", s.SprintNumber, timeRange)); err != nil {
			return "", err
		}

		if len(flatGoals) == 0 {
			if err := write("*No goals assigned.*\n"); err != nil {
				return "", err
			}
		}

		for _, g := range flatGoals {
			totalGoals++
			check := "[ ]"
			if g.Status == "completed" {
				check = "[x]"
				totalCompleted++
			}
			indent := ""
			if g.Level > 0 {
				indent = "    " // Markdown indent
			}
			if err := write(fmt.Sprintf("%s- %s %s%s\n", indent, check, g.Description, formatElapsed(g.TaskElapsedSec))); err != nil {
				return "", err
			}
		}
		if err := write("\n"); err != nil {
			return "", err
		}
	}

	// Summary Metrics
	completionRate := 0.0
	if totalGoals > 0 {
		completionRate = (float64(totalCompleted) / float64(totalGoals)) * 100
	}

	if err := write("---\n"); err != nil {
		return "", err
	}
	if err := write("### Daily Metrics\n"); err != nil {
		return "", err
	}
	if err := write(fmt.Sprintf("- **Total Goals:** %d\n", totalGoals)); err != nil {
		return "", err
	}
	if err := write(fmt.Sprintf("- **Completed:** %d\n", totalCompleted)); err != nil {
		return "", err
	}
	if err := write(fmt.Sprintf("- **Completion Rate:** %.1f%%\n", completionRate)); err != nil {
		return "", err
	}
	if err := write("\n"); err != nil {
		return "", err
	}

	// Journal
	entries, err := db.GetJournalEntries(dayID, workspaceID)
	if err != nil {
		return "", err
	}
	if len(entries) > 0 {
		if err := write("## Journal\n\n"); err != nil {
			return "", err
		}
		for _, e := range entries {
			timeStr := e.CreatedAt.Format("15:04")
			if err := write(fmt.Sprintf("- **%s**: %s\n", timeStr, e.Content)); err != nil {
				return "", err
			}
		}
	}

	return absPath, nil
}
